const productData = [
  {
    id: 1,
    name: "Kemeja Batik Biru",
    price: "Rp. 150.000",
    image: "/assets/images/rotantas.png",
    description: "Sling bag Anyaman Rotan Handmade",
    rating: 5,
  },
  {
    id: 2,
    name: "Ukiran Tembaga",
    price: "Rp. 250.000",
    image: "/assets/images/tembagakuning.png",
    description: "Kerajinan Ukiran Tembaga dan Kuningan",
    rating: 3,
  },
  {
    id: 3,
    name: "Kerajinan Gerabah",
    price: "Rp. 100.000",
    image: "/assets/images/claypot.png",
    description: "Kerajinan Gerabah",
    rating: 3,
  },
  {
    id: 4,
    name: "Gantungan topeng Jaka Baru",
    price: "Rp. 17.000",
    image: "/assets/images/topengbtk.png",
    description: "Gantungan kunci topeng Tradisional Sanggar Jaka Baru",
    rating: 4,
  },
  {
    id: 5,
    name: "Teko Set Tempurung Kelapa",
    price: "Rp. 17.000",
    image: "/assets/images/teko.png",
    description: "Teko Set Dari Tempurung Kelapa",
    rating: 3,
  },
  {
    id: 6,
    name: "Kemeja Batik Biru",
    price: "Rp. 275.000",
    image: "/assets/images/btkbirucwo.png",
    description: "Kemeja Batik Kebumen",
    rating: 5,
  },
  {
    id: 7,
    name: "Kain Lurik",
    price: "Rp. 250.000",
    image: "/assets/images/handuk.png",
    description: "Kain Lurik",
    rating: 3,
  },
  {
    id: 8,
    name: "Batik Cardigan",
    price: "Rp. 17.000",
    image: "/assets/images/batikcewe.png",
    description: "Batik Cardigan",
    rating: 5,
  },
];

export default productData;
