const ProductData = [
  {
    id: "01001",
    category: "kerajinan",
    img: "/assets/images/KERAJINANtempurungkelapa.jpeg",
    alt: "Peralatan Minum dari Tempurung Kelapa",
    title: "Peralatan Minum dari Tempurung Kelapa",
    price: "Rp. 90.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01002",
    category: "kerajinan",
    img: "/assets/images/KerajinanTopengsouvenir.jpeg",
    alt: "Gantungan Kunci Topeng Tradisional Sanggar Jaka Baru",
    title: "Gantungan Kunci Topeng Tradisional Sanggar Jaka Baru",
    price: "Rp. 17.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01003",
    category: "kerajinan",
    img: "/assets/images/celengan.jpeg",
    alt: "Celengan Kayu Handmade",
    title: "Celengan Kayu Handmade",
    price: "Rp. 70.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "01004",
    category: "kerajinan",
    img: "/assets/images/hiasanrumah.jpeg",
    alt: "Kerajinan Tempurung Kelapa untuk Hiasan Rumah",
    title: "Kerajinan Tempurung Kelapa untuk Hiasan Rumah",
    price: "Rp. 85.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01005",
    category: "kerajinan",
    img: "/assets/images/wayangsemar.jpeg",
    alt: "Wayang Semar Buatan Tangan",
    title: "Wayang Semar Buatan Tangan",
    price: "Rp. 170.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01006",
    category: "kerajinan",
    img: "/assets/images/RotanGajahTempatPermen.jpeg",
    alt: "Rotan Gajah Tempat Permen",
    title: "Rotan Gajah Tempat Permen",
    price: "Rp. 230.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01007",
    category: "kerajinan",
    img: "/assets/images/anting.jpeg",
    alt: "Anting dari Tempurung Kelapa",
    title: "Anting dari Tempurung Kelapa",
    price: "Rp. 25.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "01008",
    category: "kerajinan",
    img: "/assets/images/anyamanecenggondok.jpeg",
    alt: "Keranjang Anyaman Eceng Gondok",
    title: "Keranjang Anyaman Eceng Gondok",
    price: "Rp. 200.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "01009",
    category: "kerajinan",
    img: "/assets/images/hiasandinding.jpeg",
    alt: "Hiasan Dinding Ukiran Kayu Asli Buatan Tangan",
    title: "Hiasan Dinding Ukiran Kayu Asli Buatan Tangan",
    price: "Rp. 150.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01010",
    category: "kerajinan",
    img: "/assets/images/Lawasan_BatikTulisClassiSolo,Ca_1960.jpeg",
    alt: "Kain Batik Tulis Klasik Solo",
    title: "Kain Batik Tulis Klasik Solo",
    price: "Rp. 500.000",
    rating: 5,
  },
  {
    id: "01011",
    category: "kerajinan",
    img: "/assets/images/Kotakkayutempattishu.jpeg",
    alt: "Kotak tisu ukiran kayu asli Jepara",
    title: "Kotak tisu ukiran kayu asli Jepara",
    price: "Rp. 55.000",
    rating: 5,
  },
  {
    id: "01012",
    category: "kerajinan",
    img: "/assets/images/BatiktulisPekalongan_Privatecollection_.jpeg",
    alt: "Kain batik tulis Pekalongan",
    title: "Kain batik tulis Pekalongan",
    price: "Rp. 450.000",
    rating: 5,
  },
  {
    id: "01013",
    category: "kerajinan",
    img: "/assets/images/potrotan.jpeg",
    alt: "Pot anyaman rotan handmade",
    title: "pot anyaman rotan handmade",
    price: "Rp. 55.000",
    rating: 5,
  },
  {
    id: "01014",
    category: "kerajinan",
    img: "/assets/images/Kotakkayutempattishu.jpeg",
    alt: "Ulekan/Cobek batu asli",
    title: "Ulekan/Cobek batu asli",
    price: "Rp. 80.000",
    rating: 5,
  },
  {
    id: "01015",
    category: "kerajinan",
    img: "/assets/images/kacarotan.jpeg",
    alt: "Cermin dengan bingkai anyaman rotan",
    title: "Cermin dengan bingkai anyaman rotan",
    price: "Rp. 75.000",
    rating: 5,
  },
  {
    id: "01016",
    category: "kerajinan",
    img: "/assets/images/kaintenuntroso.jpeg",
    alt: "Kain tenun troso Jepara",
    title: "Kain tenun troso Jepara",
    price: "Rp. 105.000",
    rating: 5,
  },
  {
    id: "01017",
    category: "kerajinan",
    img: "/assets/images/ganciSolo.jpg",
    alt: "Gantungan kunci khas kota Solo",
    title: "Gantungan kunci khas kota Solo",
    price: "Rp. 4.000",
    rating: 5,
  },
  {
    id: "01018",
    category: "kerajinan",
    img: "/assets/images/topengbatik.jpg",
    alt: "Gantungan kunci topeng batik",
    title: "Gantungan kunci topeng batik",
    price: "Rp. 10.000",
    rating: 5,
  },
  {
    id: "01019",
    category: "kerajinan",
    img: "/assets/images/wayangmini.jpg",
    alt: "Wayang kulit mini",
    title: "Wayang kulit mini",
    price: "Rp. 25.000",
    rating: 5,
  },
  {
    id: "01020",
    category: "kerajinan",
    img: "/assets/images/magnetDieng.jpg",
    alt: "Magnet kulkas Dieng Jawa Tengah",
    title: "Magnet kulkas Dieng Jawa Tengah",
    price: "Rp. 15.000",
    rating: 5,
  },
  {
    id: "01021",
    category: "kerajinan",
    img: "/assets/images/magnetborobudur.jpg",
    alt: "Magnet kulkas Borobudur",
    title: "Magnet kulkas Borobudur",
    price: "Rp. 15.000",
    rating: 5,
  },
  {
    id: "01022",
    category: "kerajinan",
    img: "/assets/images/MiniaturStupaCandiBorobudur.jpeg",
    alt: "Miniatur stupa candi Borobudur",
    title: "Miniatur stupa candi Borobudur",
    price: "Rp. 25.000",
    rating: 5,
  },
  {
    id: "01023",
    category: "kerajinan",
    img: "/assets/images/blangkon.jpeg",
    alt: "Blangkon Solo murah",
    title: "Blangkon Solo murah",
    price: "Rp. 35.000",
    rating: 5,
  },

  // Makanan
  {
    id: "02001",
    category: "makanan",
    img: "/assets/images/M_gethuk.jpg",
    alt: "Gethuk khas Jawa Tengah",
    title: "Gethuk khas Jawa Tengah",
    price: "Rp. 3.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02002",
    category: "makanan",
    img: "/assets/images/M_onde2Jawa.jpeg",
    alt: "Onde-onde khas Jawa Tengah (per pcs)",
    title: "Onde-onde khas Jawa Tengah (per pcs)",
    price: "Rp. 3.500",
    rating: 4,
    isNew: true,
  },
  {
    id: "02003",
    category: "makanan",
    img: "/assets/images/M_ Wajik.jpeg",
    alt: "Wajik khas Jawa Tengah (per pcs)",
    title: "Wajik khas Jawa Tengah (per pcs)",
    price: "Rp. 2.500",
    rating: 4,
    isNew: true,
  },
  {
    id: "02004",
    category: "makanan",
    img: "/assets/images/M_lumpiaSemarang.jpeg",
    alt: "Lumpia asli Semarang (per pcs)",
    title: "Lumpia asli Semarang (per pcs)",
    price: "Rp. 10.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02005",
    category: "makanan",
    img: "/assets/images/M_wingkoBabat.jpeg",
    alt: "Wingko babat asli Jawa Tengah (per pcs)",
    title: "Wingko babat asli Jawa Tengah (per pcs)",
    price: "Rp. 7.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02006",
    category: "makanan",
    img: "/assets/images/M_serabiSolo.jpeg",
    alt: "Serabi Solo (per pcs)",
    title: "Serabi Solo (per pcs)",
    price: "Rp. 3.500",
    rating: 4,
    isNew: true,
  },
  {
    id: "02007",
    category: "makanan",
    img: "/assets/images/M_JenangMubarok.jpeg",
    alt: "Jenang Kudus Mubarok (per box)",
    title: "Jenang Kudus Mubarok (per box)",
    price: "Rp. 20.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02008",
    category: "makanan",
    img: "/assets/images/M_Rotiganjelrel.jpeg",
    alt: "Roti ganjel rel khas Semarang (per pcs)",
    title: "Roti ganjel rel khas Semarang (per pcs)",
    price: "Rp. 10.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02009",
    category: "makanan",
    img: "/assets/images/M_latopiategal.jpg",
    alt: "Latopia Tegal Ny.LIAO (per box)",
    title: "Latopia Tegal Ny.LIAO (per box)",
    price: "Rp. 20.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02010",
    category: "makanan",
    img: "/assets/images/M_Bandengpresto.jpeg",
    alt: "Bandeng Juwara-Bandeng asap presto (1 dus isi 4 ekor)",
    title: "Bandeng Juwara-Bandeng asap presto (1 dus isi 4 ekor)",
    price: "Rp. 110.000",
    rating: 4,
  },
  {
    id: "02011",
    category: "makanan",
    img: "/assets/images/M_resep-lumpia-semarang-500x375.jpg",
    alt: "Lumpia Asli Semarang (per box)",
    title: "Lumpia Asli Semarang (per box)",
    price: "Rp. 98.000",
    rating: 4,
  },
  {
    id: "02012",
    category: "makanan",
    img: "/assets/images/M_onde2Jawa.jpeg",
    alt: "Roti ganjel rel toko Oen, khas Semarang",
    title: "Roti ganjel rel toko Oen, khas Semarang",
    price: "Rp. 90.000",
    rating: 4,
  },
  {
    id: "02013",
    category: "makanan",
    img: "/assets/images/M_jenangKrasikan.jpg",
    alt: "Jenang krasikan isi 32",
    title: "Jenang krasikan isi 32",
    price: "Rp. 75.000",
    rating: 4,
  },
  {
    id: "02014",
    category: "makanan",
    img: "/assets/images/M_BapiakuBokisi20.jpg",
    alt: "BakpiaKu (1 box isi 20 psc)",
    title: "BakpiaKu (1 box isi 20 psc)",
    price: "Rp. 72.000",
    rating: 4,
  },
  {
    id: "02015",
    category: "makanan",
    img: "/assets/images/M_BakpiaKemusuk.jpg",
    alt: "Bakpia kemusuk 033 (isi 20 pcs)",
    title: "Bakpia kemusuk 033 (isi 20 pcs)",
    price: "Rp. 62.000",
    rating: 4,
  },
  {
    id: "02016",
    category: "makanan",
    img: "/assets/images/M_Yangko_Kacang_dan_Aneka_Rasa_145_Oleh_oleh_Khas_Jogja.jpg",
    alt: "Wingko wae (1 box isi 10 pcs)",
    title: "Wingko wae (1 box isi 10 pcs)",
    price: "Rp. 55.000",
    rating: 4,
  },
  {
    id: "02017",
    category: "makanan",
    img: "/assets/images/M_RotiGanjelRelToko.jpg",
    alt: "Roti ganjel rel toko Oen, khas Semarang",
    title: "Roti ganjel rel toko Oen, khas Semarang",
    price: "Rp. 90.000",
    rating: 4,
  },
  {
    id: "02018",
    category: "makanan",
    img: "/assets/images/M_Wajikwekk.jpg",
    alt: "Wajik wekk khas Magelang",
    title: "Wajik wekk khas Magelang",
    price: "Rp. 45.000",
    rating: 4,
  },
  {
    id: "02019",
    category: "makanan",
    img: "/assets/images/M_klengkam.png",
    alt: "Klengkam kering kentang Kangensolo",
    title: "Klangkeng kering kentang Kangensolo",
    price: "Rp. 30.000",
    rating: 4,
  },
  {
    id: "02020",
    category: "makanan",
    img: "/assets/images/M_JenangKudus.jpg",
    alt: "Jenang Kudus semar tiga tiga",
    title: "Jenang Kudus semar tiga tiga",
    price: "Rp. 12.000",
    rating: 4,
  },
  {
    id: "02021",
    category: "makanan",
    img: "/assets/images/M_KerupukKarpet.jpg",
    alt: "Kerupuk carpet cap Raden khas Pekalongan",
    title: "Kerupuk carpet cap Raden khas Pekalongan",
    price: "Rp. 8.000",
    rating: 4,
  },

  // Pakaian
  {
    id: "03001",
    category: "pakaian",
    img: "/assets/images/P_BATIKSOLO.jpeg",
    alt: "Kemeja batik Solo",
    title: "Kemeja batik Solo",
    price: "Rp. 250.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03002",
    category: "pakaian",
    img: "/assets/images/P_KEMEJABATIKBIRU.jpeg",
    alt: "Kemeja batik biru",
    title: "Kemeja batik biru",
    price: "Rp. 280.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03003",
    category: "pakaian",
    img: "/assets/images/P_BATIKMARK.jpeg",
    alt: "Kemeja batik Kebumen",
    title: "Kemeja batik Kebumen",
    price: "Rp. 275.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03004",
    category: "pakaian",
    img: "/assets/images/P_BATIKBLAZER.jpeg",
    alt: "Blazer batik wanita",
    title: "Blazer batik wanita",
    price: "Rp. 280.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03005",
    category: "pakaian",
    img: "/assets/images/P_BAJULURIK.jpg",
    alt: "Baju surjan/lurik",
    title: "Baju surjan/lurik",
    price: "Rp. 170.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03006",
    category: "pakaian",
    img: "/assets/images/P_KEBAWAJADUL.jpeg",
    alt: "Satu set baju kebaya jadul",
    title: "Satu set baju kebaya jadul",
    price: "Rp. 400.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03007",
    category: "pakaian",
    img: "/assets/images/P_BATIKORIGINAL.jpeg",
    alt: "Baju batik wanita original",
    title: "Baju batik wanita original",
    price: "Rp. 300.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03008",
    category: "pakaian",
    img: "/assets/images/P_BLOUSEBIRU.jpeg",
    alt: "Blouse batik kekinian",
    title: "Blouse batik kekinian",
    price: "Rp. 290.000",
    description: "Tampil trendi dengan blouse batik kekinian yang memadukan motif tradisional dengan sentuhan desain modern.",
    rating: 4,
    isNew: true,
  },
  {
    id: "03009",
    category: "pakaian",
    img: "/assets/images/P_NonararaBatik.jpeg",
    alt: "Nonarara batik",
    title: "Nonarara batik",
    price: "Rp. 250.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03010",
    category: "pakaian",
    img: "/assets/images/P_BATIKPUTIHSLIMFIT.jpeg",
    alt: "Kemeja batik pria slimfit lengan pendek",
    title: "Kemeja batik pria slimfit lengan pendek",
    price: "Rp. 300.000",
    rating: 4,
  },
  {
    id: "03011",
    category: "pakaian",
    img: "/assets/images/P_KEMEJABATIKFURING.jpg",
    alt: "Kemeja batik pria lengan panjang slimfit Premium (hitan dengan furing)",
    title: "Kemeja batik pria lengan panjang slimfit Premium (hitan dengan furing)",
    price: "Rp. 370.000",
    rating: 4,
  },
  {
    id: "03012",
    category: "pakaian",
    img: "/assets/images/P_KEMEJATIDAKFURING.jpg",
    alt: "Kemeja batik pria lengan panjang slimfit Premium (hitan abu)",
    title: "Kemeja batik pria lengan panjang slimfit Premium (hitan abu)",
    price: "Rp. 380.000",
    rating: 4,
  },
  {
    id: "03013",
    category: "pakaian",
    img: "/assets/images/P_coklatnuda.jpg",
    alt: "Baju batik Nowela series",
    title: "Baju batik Nowela series",
    price: "Rp. 440.000",
    rating: 4,
  },
  {
    id: "03014",
    category: "pakaian",
    img: "/assets/images/P_BATIKKERJA.jpg",
    alt: "Model baju batik untuk dipake kerja",
    title: "Model baju batik untuk dipake kerja",
    price: "Rp. 440.000",
    rating: 4,
  },
  {
    id: "03015",
    category: "pakaian",
    img: "/assets/images/P_GAMISOREN.jpg",
    alt: "Model batik gamis Diana series",
    title: "Model batik gamis Diana series",
    price: "Rp. 500.000",
    rating: 4,
  },
  {
    id: "03016",
    category: "pakaian",
    img: "/assets/images/P_BATIKUNGU.jpg",
    alt: "Baju batik new Queen lengan pendek",
    title: "Baju batik new Queen lengan pendek",
    price: "Rp. 420.000",
    rating: 4,
  },
  {
    id: "03017",
    category: "pakaian",
    img: "/assets/images/P_SATUSETSURJANLURIK.jpg",
    alt: "Satu set baju adat Jawa Tengah-Surjan Lurik",
    title: "Satu set baju adat Jawa Tengah-Surjan Lurik",
    price: "Rp. 300.000",
    rating: 4,
  },
  {
    id: "03018",
    category: "pakaian",
    img: "/assets/images/P_BATIKDRESSYUKA.jpg",
    alt: "Satu set dress batik Yuka (atasan dan rok lilit)",
    title: "Satu set dress batik Yuka (atasan dan rok lilit)",
    price: "Rp. 600.000",
    rating: 4,
  },
  {
    id: "03019",
    category: "pakaian",
    img: "/assets/images/P_CELANABATIK.jpeg",
    alt: "Celana motif batik",
    title: "Celana motif batik",
    price: "Rp. 35.000",
    rating: 4,
  },
  {
    id: "03020",
    category: "pakaian",
    img: "/assets/images/P_ILOVESOLO.jpg",
    alt: "Kaos I Love Solo",
    title: "Kaos I Love Solo",
    price: "Rp. 55.000",
    rating: 4,
  },
  {
    id: "03021",
    category: "pakaian",
    img: "/assets/images/P_KAOSMAGELANG.jpg",
    alt: "Kaos khas Magelang",
    title: "Kaos khas Magelang",
    price: "Rp. 60.000",
    rating: 4,
  },
  {
    id: "03022",
    category: "pakaian",
    img: "/assets/images/P_KAOSMERAH.jpg",
    alt: "Kaos Jogja premium",
    title: "Kaos Jogja premium",
    price: "Rp. 50.000",
    rating: 4,
  },
  {
    id: "03023",
    category: "pakaian",
    img: "/assets/images/P_BAJULURIKATAS.jpg",
    alt: "Baju lurik Jawa model terbaru",
    title: "Baju lurik Jawa model terbaru",
    price: "Rp. 180.000",
    rating: 4,
  },
  {
    id: "03024",
    category: "pakaian",
    img: "/assets/images/P_BAJUADATANAKC.jpg",
    alt: "Satu set baju adat Jawa Tengah",
    title: "Satu set baju adat Jawa Tengah",
    price: "Rp. 200.000",
    rating: 4,
  },
  {
    id: "03025",
    category: "pakaian",
    img: "/assets/images/P_LURIKANAK.jpeg",
    alt: "Satu set baju adat Jawa Tengah",
    title: "Satu set baju adat Jawa Tengah",
    price: "Rp. 75.000",
    rating: 4,
  },
  {
    id: "03026",
    category: "pakaian",
    img: "/assets/images/P_KAOSDISTROJOGJA.jpeg",
    alt: "Kaos distro Jogja Istimewa",
    title: "Kaos distro Jogja Istimewa",
    price: "Rp. 50.000",
    rating: 4,
  },
  {
    id: "03027",
    category: "pakaian",
    img: "/assets/images/P_KAOSPUTIH.jpg",
    alt: "Kaos Jogja model & desain terbaru",
    title: "Kaos Jogja model & desain terbaru",
    price: "Rp. 80.000",
    rating: 4,
  },
];

export default ProductData;
