export const ADataPakaian = [
  {
    id: 1,
    name: 'Kemeja Batik Solo',
    description: 'Kemeja batik khas Solo dengan desain elegan dan bahan yang nyaman dipakai.',
    price: 250000,
    image: '/assets/images/mbatikmerah.png',
    category: 'Pakaian Pria',
    material: 'Katun',
    color: 'Merah',
    size: ['M', 'L', 'XL'],
    stock: 10,
  },
  {
    id: 2,
    name: 'Kemeja Batik Biru',
    description: 'Kemeja batik dengan desain biru yang modern dan nyaman.',
    price: 280000,
    image: '/assets/images/btkbirucwo.png',
    category: 'Pakaian Pria',
    material: 'Katun Premium',
    color: 'Biru',
    size: ['L', 'XL'],
    stock: 15,
  },
  {
    id: 3,
    name: 'Kemeja Batik Kebumen',
    description: 'Kemeja batik Kebumen dengan bahan yang lembut dan nyaman.',
    price: 275000,
    image: '/assets/images/cowobatik.png',
    category: 'Pakaian Pria',
    material: 'Katun',
    color: 'Cokelat',
    size: ['M', 'L', 'XL'],
    stock: 8,
  },
  {
    id: 4,
    name: 'Blazer Batik Wanita',
    description: 'Blazer wanita dengan motif batik yang stylish dan cocok untuk acara formal.',
    price: 280000,
    image: '/assets/images/btkorencwe.png',
    category: 'Pakaian Wanita',
    material: 'Poliester',
    color: 'Oranye',
    size: ['S', 'M', 'L'],
    stock: 12,
  },
  {
    id: 5,
    name: 'Baju Surjan/Lurik',
    description: 'Baju Surjan tradisional dengan bahan nyaman, cocok untuk acara santai.',
    price: 170000,
    image: '/assets/images/bjgariscwo.png',
    category: 'Pakaian Tradisional',
    material: 'Katun',
    color: 'Hitam Putih',
    size: ['M', 'L', 'XL'],
    stock: 20,
  },
  {
    id: 6,
    name: 'Satu Set Baju Kebaya Jadul',
    description: 'Setelan kebaya jadul yang elegan, ideal untuk acara formal atau pernikahan.',
    price: 400000,
    image: '/assets/images/btk1set.png',
    category: 'Pakaian Wanita',
    material: 'Sutra',
    color: 'Hijau',
    size: ['M', 'L'],
    stock: 5,
  },
  {
    id: 7,
    name: 'Baju Batik Wanita Original',
    description: 'Baju batik wanita dengan desain klasik dan bahan yang nyaman untuk dikenakan sehari-hari.',
    price: 300000,
    image: '/assets/images/btkcoklatcwe.png',
    category: 'Pakaian Wanita',
    material: 'Katun',
    color: 'Cokelat',
    size: ['S', 'M', 'L', 'XL'],
    stock: 18,
  },
  {
    id: 8,
    name: 'Blouse Batik Kekinian',
    description: 'Blouse batik wanita yang trendy dan cocok untuk berbagai acara kasual.',
    price: 290000,
    image: '/assets/images/batikbiru.png',
    category: 'Pakaian Wanita',
    material: 'Katun Premium',
    color: 'Biru',
    size: ['M', 'L', 'XL'],
    stock: 10,
  },
  {
    id: 9,
    name: 'Nonarara Batik',
    description: 'Batik dengan motif klasik yang memberikan kesan elegan dan tradisional.',
    price: 250000,
    image: '/assets/images/btkkuningcwe.png',
    category: 'Pakaian Wanita',
    material: 'Katun',
    color: 'Kuning',
    size: ['M', 'L'],
    stock: 7,
  },
];

export default ADataPakaian;
