export const ADataKerajinan = [
  {
    id: 1,
    name: 'Peralatan Minum',
    description: 'Set peralatan minum tradisional dengan desain elegan dan bahan berkualitas.',
    price: 90000,
    image: '/assets/images/setminum.png',
    stok: 10,
    ukuran: '30x15cm',
    model: 'Set Tradisional',
    warnaTersedia: 'Cokelat, Hitam',
  },
  {
    id: 2,
    name: 'Gantungan kunci topeng',
    description: 'Gantungan kunci unik berbentuk topeng, cocok sebagai cenderamata khas.',
    price: 17000,
    image: '/assets/images/topeng.png',
    stok: 50,
    ukuran: '5x5cm',
    model: 'Miniatur',
    warnaTersedia: 'Beragam',
  },
  {
    id: 3,
    name: 'Celengan kayu handmade',
    description: 'Celengan kayu handmade dengan desain unik dan ramah lingkungan.',
    price: 70000,
    image: '/assets/images/aceleng.png',
    stok: 20,
    ukuran: '20x20x15cm',
    model: 'Klasik',
    warnaTersedia: 'Cokelat Natural',
  },
  {
    id: 4,
    name: 'Kerajinan Tempurung Kelapa',
    description: 'Kerajinan tangan dari tempurung kelapa dengan desain menarik dan fungsional.',
    price: 85000,
    image: '/assets/images/amotor.png',
    stok: 15,
    ukuran: '30x10x20cm',
    model: 'Dekoratif',
    warnaTersedia: 'Cokelat Gelap',
  },
  {
    id: 5,
    name: 'Wayang Semar',
    description: 'Patung wayang Semar, karya seni ukir khas Jawa yang penuh makna.',
    price: 170000,
    image: '/assets/images/awayang.png',
    stok: 8,
    ukuran: '50x20cm',
    model: 'Patung',
    warnaTersedia: 'Cokelat Kayu',
  },
  {
    id: 6,
    name: 'Rotan Gajah Tempat Permen',
    description: 'Tempat permen berbahan rotan berbentuk gajah, cocok untuk dekorasi rumah.',
    price: 230000,
    image: '/assets/images/agajah.png',
    stok: 5,
    ukuran: '25x25x30cm',
    model: 'Hewan',
    warnaTersedia: 'Cokelat',
  },
  {
    id: 7,
    name: 'Keranjang Anyaman',
    description: 'Keranjang anyaman tangan yang kuat dan memiliki desain natural.',
    price: 200000,
    image: '/assets/images/agondok.png',
    stok: 12,
    ukuran: '40x30x30cm',
    model: 'Kotak',
    warnaTersedia: 'Cokelat Muda',
  },
  {
    id: 8,
    name: 'Pot anyaman rotan',
    description: 'Pot bunga dari anyaman rotan dengan desain elegan dan fungsional.',
    price: 120000,
    image: '/assets/images/apot.png',
    stok: 18,
    ukuran: '20x40cm',
    model: 'Silinder',
    warnaTersedia: 'Cokelat Natural',
  },
  {
    id: 9,
    name: 'Hiasan dinding',
    description: 'Batik dengan motif klasik yang memberikan kesan elegan dan tradisional.',
    price: 150000,
    image: '/assets/images/alukisan.png',
    stok: 7,
    ukuran: '50x50cm',
    model: 'Dekorasi Dinding',
    warnaTersedia: 'Beragam',
  },
];

export default ADataKerajinan;
